import java.util.Scanner;
// in this code we have not handled the exception
// ArithmeticException

public class Day10_6 {

	public static void main(String[] args) 
	{
		int num1;
		int num2;
		int result;
		Scanner sc = new Scanner(System.in);
		
		System.out.println("Enter the first number : ");
		num1 = sc.nextInt();
		System.out.println("Enter the second number : ");
		num2 = sc.nextInt();
		result = num1/num2;
		System.out.println("Num1 = "+num1+" Num2 = "+num2+" Result = "+result);
		

	}

}
